/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    cars: Car;
    media: Media;
    brands: Brand;
    reviews: Review;
  };
  globals: {
    'about-page': AboutPage;
    'services-page': ServicesPage;
  };
}

export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
}

export interface Media {
  id: string;
  url?: string;
  updatedAt: string;
  createdAt: string;
}

export interface Car {
  id: string;
  updatedAt: string;
  createdAt: string;
}

export interface Brand {
  id: string;
  updatedAt: string;
  createdAt: string;
}

export interface Review {
  id: string;
  updatedAt: string;
  createdAt: string;
}

export interface AboutPage {
  hero: {
    heading: string;
    subheading: string;
    backgroundImageDesktop?: string | Media | null;
    backgroundImageMobile?: string | Media | null;
  };
  features?: {
    icon: string;
    title: string;
    description: string;
    id?: string | null;
  }[] | null;
  story: {
    heading: string;
    paragraph1: string;
    paragraph2: string;
    image?: string | Media | null;
  };
  whyChooseUs: {
    heading: string;
    cards?: {
      title: string;
      description: string;
      image?: string | Media | null;
      id?: string | null;
    }[] | null;
  };
}

export interface ServicesPage {
  hero: {
    heading: string;
    subheading: string;
    backgroundImage?: string | Media | null;
  };
  servicesList: {
    heading: string;
    subheading: string;
    services?: {
      icon: string;
      title: string;
      description: string;
      image?: string | Media | null;
      id?: string | null;
    }[] | null;
  };
}
